In [45]:
import numpy as np
from math import floor

def MyHOSobol(m, s, d):
    # Higher order Sobol sequence
    # Create a higher order Sobol sequence.
    # 2^m number of points
    # s dimension of final point set
    # d interlacing factor
    # X Output Sobol sequence
    z = np.loadtxt('sobol.dat')
    z = z[:pow(2, m), :s*d]
    if d > 1:
        N = pow(2, m) # Number of points;
        u = 52
        depth = floor(u/d)

        # Create binary representation of digits;

        W = z * pow(2, depth)
        Z = floor(np.transpose(W))
        Y = np.zeros((s, N))
        for j in range(1, s+1):
            for i in range(1, depth+1):
                for k in range(1, d+1):
                    Y[j-1,:] = np.bitset( Y[j-1,:],(depth*d+1) - k - (i-1)*d,np.bitget( Z[(j-1)*d+k-1,:],(depth+1) - i))
        Y = Y * pow(2, -depth*d)

        X = np.transpose(Y) # X is matrix of higher order Sobol points,
        # where the number of columns equals the dimension
        # and the number of rows equals the number of points;

    else:
        X = z

    return X


In [46]:
MyHOSobol(5,3,2)

TypeError: only size-1 arrays can be converted to Python scalars

In [12]:
def MyHOSobol(m, s, d):
    # Higher order Sobol sequence
    # Create a higher order Sobol sequence.
    # 2^m number of points
    # s dimension of final point set
    # d interlacing factor
    # X Output Sobol sequence
    with open('sobol.dat') as f:
        z = [list(map(float,line.split())) for line in f]
    z = z[:2**(m)][:s*d]

    if d > 1:
        N = pow(2, m) # Number of points;
        u = 52
        depth = u // d

        # Create binary representation of digits;

        W = [[x * pow(2, depth) for x in row] for row in z]
        Z = [[int(x) for x in row] for row in W]
        Y = [[0 for _ in range(N)] for _ in range(s)]
        for j in range(s):
            for i in range(depth):
                for k in range(d):
                    
                    Y[j, :] & ~(1 << ((depth*d+1) - k - (i-1)*d)) | (((Z[(j-1)*d+k,:] >> ((depth+1) - i)) & 1) << ((depth*d+1) - k - (i-1)*d))
        Y = Y * 2**(-depth*d)
        X = Y.T  # X is matrix of higher order Sobol points,
        # where the number of columns equals the dimension
        # and the number of rows equals the number of points;
    
    else:
        X = z

    return X
m = 5; s = 3; d = 2;  
MyHOSobol(5,3,2)

0


TypeError: list indices must be integers or slices, not tuple

In [11]:
for j in range(s):
    print(j)
    
#Y
N = pow(2, m) # Number of points;
Y = [[0 for _ in range(N)] for _ in range(s)]
Y[1, :]

0
1
2


TypeError: list indices must be integers or slices, not tuple

In [48]:
def MyHOSobol(m, s, d):
    # Higher order Sobol sequence
    # Create a higher order Sobol sequence.
    # 2^m number of points
    # s dimension of final point set
    # d interlacing factor
    # X Output Sobol sequence
    z = np.loadtxt('sobol.dat')
    z = z[:2**m, :s*d]

    if d > 1:
        N = 2**m  # Number of points;
        u = 52
        depth = u // d

        # Create binary representation of digits;

        W = z * 2**depth
        Z = np.floor(W.T)
        Y = np.zeros((s, N))
        for j in range(s):
            for i in range(depth):
                for k in range(d):
                    Y[j, :] = (Y[j, :] & ~(1 << ((depth*d+1) - k - (i-1)*d))) | (((Z[(j-1)*d+k,:] >> ((depth+1) - i)) & 1) << ((depth*d+1) - k - (i-1)*d))

        Y = Y * 2**(-depth*d)

        X = Y.T  # X is matrix of higher order Sobol points,
        # where the number of columns equals the dimension
        # and the number of rows equals the number of points;

    else:
        X = z

    return X

In [61]:
m = 5; s = 3; d = 2;  #MyHOSobol(5,3,2)

In [56]:
z = np.loadtxt('sobol.dat')

In [51]:
z


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.00000000e-01, 5.00000000e-01, 5.00000000e-01, ...,
        5.00000000e-01, 5.00000000e-01, 5.00000000e-01],
       [7.50000000e-01, 2.50000000e-01, 2.50000000e-01, ...,
        2.50000000e-01, 2.50000000e-01, 7.50000000e-01],
       ...,
       [7.50244141e-01, 6.91162109e-01, 8.42285156e-02, ...,
        1.53564453e-01, 7.11669922e-01, 2.12646484e-01],
       [5.00244141e-01, 4.41162109e-01, 8.34228516e-01, ...,
        9.03564453e-01, 4.61669922e-01, 4.62646484e-01],
       [2.44140625e-04, 9.41162109e-01, 3.34228516e-01, ...,
        4.03564453e-01, 9.61669922e-01, 9.62646484e-01]])

In [52]:
z = z[:2**5, :3*2]

In [53]:
z

array([[0.     , 0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.5    , 0.5    , 0.5    , 0.5    , 0.5    , 0.5    ],
       [0.75   , 0.25   , 0.25   , 0.25   , 0.75   , 0.75   ],
       [0.25   , 0.75   , 0.75   , 0.75   , 0.25   , 0.25   ],
       [0.375  , 0.375  , 0.625  , 0.875  , 0.375  , 0.125  ],
       [0.875  , 0.875  , 0.125  , 0.375  , 0.875  , 0.625  ],
       [0.625  , 0.125  , 0.875  , 0.625  , 0.625  , 0.875  ],
       [0.125  , 0.625  , 0.375  , 0.125  , 0.125  , 0.375  ],
       [0.1875 , 0.3125 , 0.9375 , 0.4375 , 0.5625 , 0.3125 ],
       [0.6875 , 0.8125 , 0.4375 , 0.9375 , 0.0625 , 0.8125 ],
       [0.9375 , 0.0625 , 0.6875 , 0.1875 , 0.3125 , 0.5625 ],
       [0.4375 , 0.5625 , 0.1875 , 0.6875 , 0.8125 , 0.0625 ],
       [0.3125 , 0.1875 , 0.3125 , 0.5625 , 0.9375 , 0.4375 ],
       [0.8125 , 0.6875 , 0.8125 , 0.0625 , 0.4375 , 0.9375 ],
       [0.5625 , 0.4375 , 0.0625 , 0.8125 , 0.1875 , 0.6875 ],
       [0.0625 , 0.9375 , 0.5625 , 0.3125 , 0.6875 , 0.

In [58]:
N = 2**m
N

32

In [59]:
u = 52

In [62]:
depth = u // d

In [63]:
depth

26

In [65]:
W = z * 2**depth
W

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [3.3554432e+07, 3.3554432e+07, 3.3554432e+07, ..., 3.3554432e+07,
        3.3554432e+07, 3.3554432e+07],
       [5.0331648e+07, 1.6777216e+07, 1.6777216e+07, ..., 1.6777216e+07,
        1.6777216e+07, 5.0331648e+07],
       ...,
       [5.0348032e+07, 4.6383104e+07, 5.6524800e+06, ..., 1.0305536e+07,
        4.7759360e+07, 1.4270464e+07],
       [3.3570816e+07, 2.9605888e+07, 5.5984128e+07, ..., 6.0637184e+07,
        3.0982144e+07, 3.1047680e+07],
       [1.6384000e+04, 6.3160320e+07, 2.2429696e+07, ..., 2.7082752e+07,
        6.4536576e+07, 6.4602112e+07]])

In [66]:
Z = np.floor(W.T)
Z

array([[0.0000000e+00, 3.3554432e+07, 5.0331648e+07, ..., 5.0348032e+07,
        3.3570816e+07, 1.6384000e+04],
       [0.0000000e+00, 3.3554432e+07, 1.6777216e+07, ..., 4.6383104e+07,
        2.9605888e+07, 6.3160320e+07],
       [0.0000000e+00, 3.3554432e+07, 1.6777216e+07, ..., 5.6524800e+06,
        5.5984128e+07, 2.2429696e+07],
       ...,
       [0.0000000e+00, 3.3554432e+07, 1.6777216e+07, ..., 1.0305536e+07,
        6.0637184e+07, 2.7082752e+07],
       [0.0000000e+00, 3.3554432e+07, 1.6777216e+07, ..., 4.7759360e+07,
        3.0982144e+07, 6.4536576e+07],
       [0.0000000e+00, 3.3554432e+07, 5.0331648e+07, ..., 1.4270464e+07,
        3.1047680e+07, 6.4602112e+07]])

In [68]:
W = [[x * pow(2, depth) for x in row] for row in z]
W

[[0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  33554432.0,
  335

In [70]:
Y = np.zeros((s, N))
Y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
Z = [[int(x) for x in row] for row in W]
Z
    

In [72]:
Y = [[0 for _ in range(N)] for _ in range(s)]

In [ ]:
Y