# Brownian Bridge Demo

In [1]:
import numpy as np
import qmcpy as qp

In [4]:
x = qp.BrownianMotion(qp.DigitalNetB2(3)).gen_samples(4)
print(x)

[[-0.00402083 -0.395481    0.80068742]
 [-0.26000562  0.03562909 -1.12191135]
 [ 0.68190517  0.98988106  0.87294418]
 [-0.00354023 -0.0697883  -0.02541126]]


In [7]:
n = 2**10
sob = qp.Sobol(dimension=3)
brown_sob_PCA = qp.BrownianMotion(sob,decomp_type='PCA')
xbsp = brown_sob_PCA.gen_samples(n)
print(xbsp)

[[-1.06047487 -1.67099    -1.24512934]
 [ 0.46907417  0.92529584  0.58120814]
 [ 0.34996842  0.42366852 -0.61960079]
 ...
 [ 1.24534078  1.13402305  1.66091405]
 [ 0.27285006 -0.26742576 -1.08719898]
 [-0.13857775 -0.02288358  0.14966825]]


In [11]:
mean_xbsp = np.mean(xbsp,axis=0)
var_xbsp = np.var(xbsp,axis=0)
print(mean_xbsp)
print(var_xbsp)

[-0.00039488 -0.00078369 -0.00106133]
[0.33261376 0.66590853 1.00067375]
