# Brownian Bridge Demo

In [1]:
import numpy as np
import qmcpy as qp

In [2]:
x = qp.BrownianMotion(qp.DigitalNetB2(3)).gen_samples(4)
print(x)

AttributeError: type object 'super' has no attribute '_transform'

In [ ]:
n = 2**10
sob = qp.Sobol(dimension=3)
brown_sob_PCA = qp.BrownianMotion(sob,decomp_type='PCA')
xbsp = brown_sob_PCA.gen_samples(n)
print(xbsp)

[[ 0.88327282  1.15449934  0.85655168]
 [-0.27156816 -1.04270013 -0.73687188]
 [-0.27437183 -0.0793467   0.51818884]
 ...
 [-1.09954062 -1.13146892 -1.82776102]
 [-0.27210368  0.31331612  0.75463122]
 [ 0.56661789 -0.46862537  0.12303735]]


In [ ]:
mean_xbsp = np.mean(xbsp,axis=0)
var_xbsp = np.var(xbsp,axis=0)
print(mean_xbsp)
print(var_xbsp)

[ 1.53331369e-05  7.40620140e-05 -5.63374976e-05]
[0.33305733 0.66504598 0.9974356 ]
