# Documenting Python Ways

## Import Needed Packages

In [1]:
import matplotlib.pyplot as plt
import math
import numpy as np
import qmcpy as qp
from simple_colors import *

## Printing

In [2]:
pi = np.pi
print("The variable a is",pi,f"or",green('approximately', ['underlined', 'bold', 'italic']),f"the value {pi:.4f}")  
    #labeling the output and using f-strings and colors
print("The variable pi is approximately %.4f but not %.8e"%(pi,np.e))  

The variable a is 3.141592653589793 or approximately the value 3.1416
The variable pi is approximately 3.1416 but not 2.71828183e+00


In [3]:
print('Hello world',end = '', flush = True)  #controling line feeds
print('Goodbye world')

Hello worldGoodbye world


## Variables and arrays

### Initializing

In [4]:
x = np.zeros(5,dtype=bool)  #initialize an array with Boolean entries
x[2]=True
print("x =",x)

x = [False False  True False False]


In [49]:
y = np.array([range(9),range(29,47,2)]).T  #initialize two dimensional array using the range command
print('y =',y)
y = np.vstack((y,y[:3])) #copying top three rows to the bottom by vstack
print('y = ',y)
y = np.hstack((y,y[:,1,None])) #copying second column to the right by hstack
print('y = ',y)

y = [[ 0 29]
 [ 1 31]
 [ 2 33]
 [ 3 35]
 [ 4 37]
 [ 5 39]
 [ 6 41]
 [ 7 43]
 [ 8 45]]
y =  [[ 0 29]
 [ 1 31]
 [ 2 33]
 [ 3 35]
 [ 4 37]
 [ 5 39]
 [ 6 41]
 [ 7 43]
 [ 8 45]
 [ 0 29]
 [ 1 31]
 [ 2 33]]
y =  [[ 0 29 29]
 [ 1 31 31]
 [ 2 33 33]
 [ 3 35 35]
 [ 4 37 37]
 [ 5 39 39]
 [ 6 41 41]
 [ 7 43 43]
 [ 8 45 45]
 [ 0 29 29]
 [ 1 31 31]
 [ 2 33 33]]


### Accessing subarrays

In [52]:
u = y[-3:,]  #last three rows
print('u = ',u)

u =  [[ 0 29 29]
 [ 1 31 31]
 [ 2 33 33]]


In [53]:
z = y[(y[:,0] <= 3),:]  #choose only those rows that meet a certain criterion
w = y[:,(y.sum(0) > 100)]  #or choose only those columns that meet a certain criterion, note that "sum" is a method
print('z =',z,'\nw =',w)  #\n means new line

z = [[ 0 29 29]
 [ 1 31 31]
 [ 2 33 33]
 [ 3 35 35]
 [ 0 29 29]
 [ 1 31 31]
 [ 2 33 33]] 
w = [[29 29]
 [31 31]
 [33 33]
 [35 35]
 [37 37]
 [39 39]
 [41 41]
 [43 43]
 [45 45]
 [29 29]
 [31 31]
 [33 33]]


### Methods (functions) for arrays

For more see [this link](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

In [13]:
mean = y.mean(0)
std = y.std(0,ddof=1)  #unbiased standard deviation
# also, min, max, argmin, argmax, 
print('mean and standard deviation are \n',mean,std)
sumofmeans = y.mean(0).sum()
prodofmeans = y.mean(0).prod()
print('sum of means is', sumofmeans, 'and their product is', prodofmeans)

mean and standard deviation are 
 [ 4. 37.] [2.73861279 5.47722558]
sum of means is 41.0 and their product is 148.0


## Plotting

In [ ]:
n = 64
d = 3
xpts = qp.Sobol(d, randomize = False).gen_samples(n)  #unscrambled Sobol points

### 1-Dimensional Plot

In [ ]:
fig, ax = plt.subplots()
ax.plot(xpts[:,0], np.zeros_like(xpts[:,0]), 'b.', markersize = 10, zorder=10, clip_on=False)  #just the first coordinate
ax.set_ylim([0, 3e-2])
ax.set_title(f"{n:.0f} Equally Spaced Points")
ax.set_xlabel("$x_i$")
ax.set_aspect(1)
ax.axes.get_yaxis().set_visible(False)  #turn off the tics on the vertical axis
ax.spines[['top','right','left']].set_visible(False)  #turn off the bounding box on the top and sides

### 2-Dimensional Plot

### 2-D Plot with Different Scales
[See this url for details](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/two_scales.html)

## Making Colab Notebooks

## Images 
See [this link](https://medium.com/@yogeshkd/four-ways-to-embed-images-in-your-jupyter-notebook-powered-blog-2d28f6d1b6e6) for more information